services:
  base-image-jre:
    extends:
      file: templates.yml
      service: multi-platform
    image: ${REPOSITORY}/gs-cloud-base-jre:${TAG}
    build:
      context: ../src/apps/base-images/jre/

  base-image-spring-boot:
    extends:
      file: templates.yml
      service: multi-platform
    image: ${REPOSITORY}/gs-cloud-base-spring-boot:${TAG}
    depends_on: [base-image-jre]
    build:
      context: ../src/apps/base-images/spring-boot/

  base-image-geoserver:
    extends:
      file: templates.yml
      service: multi-platform
    image: ${REPOSITORY}/gs-cloud-base-geoserver-image:${TAG}
    depends_on: [base-image-spring-boot]
    build:
      context: ../src/apps/base-images/geoserver/
