services:
  config:
    extends:
      file: templates.yml
      service: multi-platform
    image: ${REPOSITORY}/geoserver-cloud-config:${TAG}
    build:
      context: ../src/apps/infrastructure/config/

  gateway-webmvc:
    extends:
      file: templates.yml
      service: multi-platform
    image: ${REPOSITORY}/geoserver-cloud-gateway:${TAG}
    build:
      context: ../src/apps/infrastructure/gateway-webmvc/

  gateway-webflux:
    extends:
      file: templates.yml
      service: multi-platform
    image: ${REPOSITORY}/geoserver-cloud-gateway:${TAG}
    build:
      context: ../src/apps/infrastructure/gateway-webflux/
