name: gscloud_dev_pgconfig

volumes:
  pgconfigdb_data: # volume for postgresql data, used to store the geoserver config through pgconfig backend

x-gs-dependencies: &gs-dependencies
  pgconfigdb:
    condition: service_started
    required: true

#
# Configures all geoserver services to use the postgresql database server with pgconfig as catalog backend.
# Run with `docker compose -f compose.yml -f catalog-pgconfig.yml up -d`
x-geoserver-env: &geoserver_environment
  SPRING_PROFILES_ACTIVE: "${GEOSERVER_DEFAULT_PROFILES},pgconfig"

services:
  pgconfigdb:
    extends:
      file: templates.yml
      service: pgconfigdbtemplate
    volumes:
      - pgconfigdb_data:/var/lib/postgresql/data
    ports:
      - 8432:5432

  wfs:
    environment: *geoserver_environment
    depends_on: *gs-dependencies

  wms:
    environment: *geoserver_environment
    depends_on: *gs-dependencies

  wcs:
    environment: *geoserver_environment
    depends_on: *gs-dependencies

  rest:
    environment: *geoserver_environment
    depends_on: *gs-dependencies

  webui:
    environment: *geoserver_environment
    depends_on: *gs-dependencies

  gwc:
    environment: *geoserver_environment
    depends_on: *gs-dependencies

  wps:
    environment: *geoserver_environment
    depends_on: *gs-dependencies
