volumes:
  #rabbitmq_data: # volume for rabbitmq data, so it doesn't create an anonymous one on each container
  postgis_data:
  acl_data:

services:
  postgis:
    extends:
      file: templates.yml
      service: postgistemplate
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - 6432:5432
 
  acldb:
    extends:
      file: templates.yml
      service: acldbtemplate
    volumes:
      - acl_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    user: ${GS_USER}
    tmpfs:
      - /var/lib/rabbitmq
    volumes:
      - $PWD/../config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:Z
    #  - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics is_running
      start_period: 10s
      interval: 15s
      timeout: 30s
      retries: 3

  admin:
    image: ${REPOSITORY}/geoserver-cloud-admin-server:${TAG}
    user: ${GS_USER}
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - 9091:8080
    deploy:
      mode: replicated
      replicas: 0
      resources:
        limits:
          cpus: '2.0'
          memory: 512M

  # Sample LDAP server to test LDAP Auth against
  # Go to Authentication -> Authentication Providers -> Add new -> LDAP
  # * Server URL: ldap://ldap:389/dc=georchestra,dc=org
  # * User lookup pattern: uid={0},ou=users
  # * Use LDAP groups for authorization: check
  # * Enable Hierarchical groups search: check
  # * Nested group search filter: member={0}
  # Save
  # Provider Chain -> add the ldap provider to the "Selected" list
  # Save
  # Then login with either testadmin/testadmin or testuser/testuser
  ldap:
    image: georchestra/ldap:latest
    environment:
        - SLAPD_ORGANISATION=georchestra
        - SLAPD_DOMAIN=georchestra.org
        - SLAPD_PASSWORD=secret
        - SLAPD_LOG_LEVEL=32768 # See https://www.openldap.org/doc/admin24/slapdconfig.html#loglevel%20%3Clevel%3E
    restart: unless-stopped
    ports:
      - 389:389
    deploy:
      mode: replicated
      replicas: 0
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
