apiVersion: v1
data:
  acl.yaml: |-
    jndi.acldb.enabled: true
    acl.db.jndiName: java:comp/env/jdbc/acl
    acl.caching: true

    geoserver.acl.security:
      headers:
        enabled: false
        user-header: sec-username
        roles-header: sec-roles
        admin-roles: ROLE_ADMINISTRATOR
      basic:
        enabled: true
        users:
          admin:
            enabled: true
            admin: true
            password: "{noop}GEOSERVER-PASSWORD"

    rabbitmq:
        host: rabbitmq
        port: 5672
        user: guest
        password: guest

    logging:
      level:
        root: warn
        org.geoserver.acl: info
        org.geoserver.cloud.config: info
        org.springframework.jdbc.support: info
        org.springframework.security: debug

    jndi:
      acldb.enabled: true
      datasources:
        pgconfig:
          enabled: true
          schema: acl
          wait-for-it: true
          wait-timeout: 100
          url: jdbc:postgresql://database:5432/pgconfig
          username: pgconfig
          password: ACL_PASSWORD
          maximum-pool-size: 10
          minimum-idle: 0
          connection-timeout: 5000
          idle-timeout: 120000
          
kind: ConfigMap
metadata:
  name: acl-configmap
  namespace: KUBERNETES-NAMESPACE

