rabbitmq:
  enabled: true
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 0.1
      memory: 512Mi
  auth:
    username: geoserver
    password: password
    erlangCookie: cookie
  persistence:
    enabled: false

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        # this should be replaced by your existing secret
        # existingSecret: your-secret-name
        postgresPassword: g30s3rv3r
  primary:
    initdb:
      # install postgis extension
      scriptsConfigMap: install-postgis-configmap

additionalVolumes: &additional-volumes
  cache:
    emptyDir: {}

additionalVolumeMounts: &additional-volume-mounts
  /mnt/cache:
    name: 'cache'

env: &env-override
  PG_PASSWORD:
    type: secret
    name: 'gs-cloud-pgconfig-postgresql'
    key: 'postgres-password'
  RABBITMQ_HOST:
    value: 'gs-cloud-pgconfig-rabbitmq'
  RABBITMQ_USER:
    value: 'geoserver'
  RABBITMQ_PASSWORD:
    type: secret
    name: 'gs-cloud-pgconfig-rabbitmq'
    key: 'rabbitmq-password'
  SPRING_PROFILES_ACTIVE:
    value: standalone,pgconfig
  GEOWEBCACHE_CACHE_DIR:
    value: '/mnt/cache'
  JAVA_OPTS:
    value: '$(JAVA_OPTS_DEFAULT) -XshowSettings:system'
  PGCONFIG_HOST:
    value: gs-cloud-pgconfig-postgresql-hl
  PGCONFIG_PORT:
    value: '5432'
  PGCONFIG_DATABASE:
    value: postgres
  PGCONFIG_SCHEMA:
    value: pgconfig
  PGCONFIG_USERNAME:
    value: postgres
  PGCONFIG_PASSWORD:
    type: secret
    name: 'gs-cloud-pgconfig-postgresql'
    key: 'postgres-password'
  PGCONFIG_MAXCONNECTIONS:
    value: '10'

additional-stuff: &additional-stuff
  volumes:
    <<: *additional-volumes
  containers:
    spring:
      env:
        <<: *env-override
      volumeMounts:
        <<: *additional-volume-mounts

geoservercloud:
  global:
    profile: standalone,pgconfig
    image:
      pullPolicy: IfNotPresent
  geoserver:
    ingress:
      enabled: true
      hostGroups:
        host1:
          tls:
            enabled: false
          hosts:
            - gscloud.local
    services:
      gateway:
        ingress:
          enabled: true
        <<: *additional-stuff
      webui:
        <<: *additional-stuff
      rest:
        replicaCount: 1
        <<: *additional-stuff
      wms:
        replicaCount: 1
        <<: *additional-stuff
      wcs:
        replicaCount: 1
        <<: *additional-stuff
      wfs:
        replicaCount: 1
        <<: *additional-stuff
      gwc:
        replicaCount: 0
        <<: *additional-stuff
      wps:
        enabled: true
        replicaCount: 1
        <<: *additional-stuff
