apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: KUBERNETES-NAMESPACE
  labels:
    component: database
spec:
  selector:
    component: database
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007
