apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: geoserver
    type: database-storage
  name: database-pvc
  namespace: KUBERNETES-NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
  selector:
    matchLabels:
      name: database-pv