apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: KUBERNETES-NAMESPACE
  labels:
    component: database
spec:
  selector:
    component: database
  ports:
    - protocol: TCP
      port: 5432