/* (c) 2026 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */
package org.geoserver.spring.config.transpiler.generator;

import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import org.geoserver.spring.config.transpiler.context.TranspilationContext;

/**
 * Main generator that generates the complete JavaFile from XML configuration.
 *
 * <p>This generator orchestrates the entire code generation process by:
 *
 * <ul>
 *   <li>Creating the main {@code @Configuration} class structure
 *   <li>Delegating to specialized generators for different aspects
 *   <li>Assembling the final JavaFile with proper imports and formatting
 * </ul>
 *
 * <p>The strategy pattern allows for clean separation of concerns where each generator specializes in generating
 * specific types of code while this top-level generator coordinates the overall process.
 *
 * @since 3.0.0
 * @see TranspilationContext
 * @see BeanMethodGenerator
 */
public class JavaFileGenerator {

    private final ConfigurationClassGenerator configurationClassGenerator;

    /** Create a new JavaFile generator with default generator implementations. */
    public JavaFileGenerator() {
        this.configurationClassGenerator = new ConfigurationClassGenerator();
    }

    /**
     * Generate a complete JavaFile from the transpilation context.
     *
     * @param context the transpilation context containing all configuration
     * @return the generated JavaFile ready to be written
     */
    public JavaFile generateJavaFile(TranspilationContext context) {

        // Generate the main {@code @Configuration} class
        TypeSpec configurationClass = configurationClassGenerator.generateConfigurationClass(context);

        // Create and return the JavaFile
        return JavaFile.builder(context.getTargetPackage(), configurationClass)
                .addFileComment("Generated by XML Configuration Transpiler")
                .addFileComment("Source: " + String.join(", ", context.getXmlLocations()))
                .build();
    }
}
