/* (c) 2026 Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 */
package org.geoserver.spring.config.transpiler.generator;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterSpec;
import java.lang.reflect.Constructor;
import java.util.List;
import java.util.Objects;
import javax.lang.model.element.Modifier;
import org.geoserver.spring.config.transpiler.context.BeanGenerationContext;
import org.geoserver.spring.config.transpiler.context.TranspilationContext;
import org.geoserver.spring.config.transpiler.xml.EnhancedBeanDefinition;
import org.jspecify.annotations.Nullable;
import org.springframework.beans.PropertyValue;
import org.springframework.beans.PropertyValues;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.beans.factory.config.RuntimeBeanReference;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;

/**
 * Fallback (low priority) generator for generating {@code @Bean} methods for simple beans.
 *
 * <p>This generator handles the simplest case of Spring bean definitions: beans with no constructor arguments, no
 * factory methods, and minimal configuration. It serves as a fallback when more specialized generators cannot handle a
 * particular bean definition.
 *
 * <p>Generated {@code @Bean} methods will use default (no-argument) constructors and may apply property values using
 * setter methods if needed.
 *
 * @since 3.0.0
 */
public class SimpleBeanMethodGenerator extends AbstractBeanMethodGenerator {

    @Override
    public boolean canHandle(BeanDefinition beanDefinition) {
        // Handle simple beans as a fallback
        // This should handle beans that other generators can't process
        return beanDefinition.getBeanClassName() != null && !beanDefinition.isAbstract();
    }

    @Override
    public MethodSpec generateBeanMethod(BeanGenerationContext beanContext) {
        TranspilationContext transpilationContext = beanContext.getTranspilationContext();
        BeanDefinition beanDefinition = beanContext.getBeanDefinition();
        String beanName = beanContext.getBeanName();
        String beanClassName = Objects.requireNonNull(beanContext.getBeanClassName());

        // Sanitize bean name for method name
        String methodName = EnhancedBeanDefinition.sanitizeBeanName(beanName);

        // For auto-generated bean names, add unique suffix to avoid collisions across configurations
        if (beanContext.isAutoGenerated()) {
            String uniqueSuffix = transpilationContext.getUniqueMethodSuffix();
            methodName = methodName + "_" + uniqueSuffix;
        }

        // {@code @Bean} methods are always package-private per Spring conventions
        // Only {@code @Configuration} class visibility is controlled by publicAccess
        Modifier[] methodModifiers = new Modifier[0]; // Package-private

        // Get return type using TypeNameResolver
        ClassName returnType = getReturnType(beanContext, transpilationContext);

        // Create method builder
        MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder(methodName)
                .addModifiers(methodModifiers)
                .returns(returnType);

        // Add {@code @Bean} annotation with proper name handling
        methodBuilder.addAnnotation(createBeanAnnotation(beanContext));

        // Add @SuppressWarnings if needed for managed collections
        addSuppressWarningsIfNeeded(methodBuilder, beanDefinition);

        // Add @Lazy annotation if bean has lazy-init="true"
        if (beanDefinition.isLazyInit()) {
            methodBuilder.addAnnotation(Lazy.class);
        }

        // Add @Scope annotation if bean has non-default scope
        @Nullable String scope = beanDefinition.getScope();
        if (scope != null && !scope.isEmpty() && !"singleton".equals(scope)) {
            AnnotationSpec scopeAnnotation = AnnotationSpec.builder(Scope.class)
                    .addMember("value", "$S", scope)
                    .build();
            methodBuilder.addAnnotation(scopeAnnotation);
        }

        // Add @DependsOn annotation if bean has depends-on attribute
        addDependsOnAnnotation(methodBuilder, beanDefinition.getDependsOn());

        // Add javadoc using enhanced bean info
        String javadocContent = beanContext.generateJavadoc();
        methodBuilder.addJavadoc(javadocContent);

        // Generate method body
        generateMethodBody(methodBuilder, beanContext, beanDefinition, beanClassName, returnType, transpilationContext);

        return methodBuilder.build();
    }

    @Override
    public int getPriority() {
        return 200; // Low priority - fallback generator
    }

    /** Generate the method body for simple bean creation. */
    private void generateMethodBody(
            MethodSpec.Builder methodBuilder,
            BeanGenerationContext beanContext,
            BeanDefinition beanDefinition,
            String beanClassName,
            ClassName returnType,
            TranspilationContext transpilationContext) {

        // Resolve constructor once upfront (no-arg for simple beans)
        Constructor<?> constructor = Reflections.resolveTargetConstructor(beanContext.getResolvedBeanClass(), null);
        boolean needsReflection = constructor != null && !Reflections.isPublic(constructor);

        // Add constructor exceptions to method signature
        addExceptionsFromConstructor(methodBuilder, constructor, needsReflection);

        boolean hasProperties = beanContext.hasPropertyValues();

        if (hasProperties) {
            // Need to handle property values
            methodBuilder.addJavadoc("Note: Property values will be applied using setter methods\n");

            // Collect bean references from properties with original (unsanitized) names — needed
            // both for @Qualifier (Spring looks up by the literal bean name, preserving dots) and
            // for finding the matching property by name in the PropertyValues.
            List<String> originalBeanReferences =
                    super.collectPropertyBeanReferences(beanDefinition.getPropertyValues());
            // Parallel list of sanitized identifiers to use as Java parameter/variable names.
            List<String> sanitizedBeanReferences = originalBeanReferences.stream()
                    .map(EnhancedBeanDefinition::sanitizeBeanName)
                    .toList();

            // Add method parameters for property bean references with proper types
            for (int i = 0; i < originalBeanReferences.size(); i++) {
                String originalBeanRef = originalBeanReferences.get(i);
                String sanitizedBeanRef = sanitizedBeanReferences.get(i);

                // Find the property name for this bean reference (uses original name to match PropertyValues)
                String propertyName = findPropertyNameForBeanRef(originalBeanRef, beanDefinition.getPropertyValues());

                // Use enhanced type inference from base class
                ClassName paramType = resolveParameterTypeWithInference(
                        originalBeanRef, beanClassName, null, propertyName, null, transpilationContext);

                ParameterSpec.Builder paramBuilder = ParameterSpec.builder(paramType, sanitizedBeanRef)
                        .addAnnotation(AnnotationSpec.builder(Qualifier.class)
                                .addMember("value", "$S", originalBeanRef)
                                .build());
                methodBuilder.addParameter(paramBuilder.build());
            }

            // Create bean instance and set properties
            if (needsReflection) {
                generateReflectionConstructorCall(methodBuilder, beanClassName, returnType, "bean");
            } else {
                methodBuilder.addStatement("$T bean = new $T()", returnType, returnType);
            }
            // Pass the sanitized list — generatePropertySetters uses these as Java identifiers in the body.
            generatePropertySetters(
                    methodBuilder,
                    beanDefinition.getPropertyValues(),
                    sanitizedBeanReferences,
                    beanClassName,
                    beanContext.getBeanName());
            methodBuilder.addStatement("return bean");
        } else {
            // Simple case: no properties - direct instantiation
            if (needsReflection) {
                generateReflectionConstructorCall(methodBuilder, beanClassName, returnType, null);
            } else {
                methodBuilder.addStatement("return new $T()", returnType);
            }
        }
    }

    private ClassName getReturnType(BeanGenerationContext beanContext, TranspilationContext context) {
        return resolveReturnType(beanContext.getBeanDefinition(), context);
    }

    /** Find the property name that references a specific bean. */
    private String findPropertyNameForBeanRef(String beanRef, PropertyValues propertyValues) {
        for (PropertyValue pv : propertyValues.getPropertyValues()) {
            Object value = pv.getValue();
            if (value instanceof RuntimeBeanReference ref && ref.getBeanName().equals(beanRef)) {
                return pv.getName();
            }
        }
        return null;
    }
}
